apt:
  repositories:
    weechat:
      url: https://weechat.org/debian
      key: 11E9DE8848F2B65222AA75B8D1820DB22A11534E

    tor:
      url: https://deb.torproject.org/torproject.org
      key: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
      keyring: deb.torproject.org-keyring.gpg

  packages:
    tor:
      - name: deb.torproject.org-keyring
      - name: python-torctl
      - name: tor
      - name: torsocks
      - name: tor-arm

    misc:
      - name: acl
      - name: acpi
      - name: acpi-support-base
      - name: acpid
      - name: adduser
      - name: aglfn
      - name: alpine
      - name: anarchism
      - name: ansible
      - name: apt
      - name: apt-file
      - name: apt-transport-https
      - name: apt-utils
      - name: aptitude
      - name: aptitude-common
      - name: aria2
      - name: aspell
      - name: aspell-en
      - name: atool
      - name: auditd
      - name: autoconf
      - name: automake
      - name: autopoint
      - name: autotools-dev
      - name: awscli
      - name: base-files
      - name: base-passwd
      - name: bash
      - name: bash-completion
      - name: bastet
      - name: bc
      - name: bcrypt
      - name: binfmt-support
      - name: binutils
      - name: bitlbee
      - name: bitlbee-common
      - name: bsdgames
      - name: bsdmainutils
      - name: bsdutils
      - name: build-essential
      - name: busybox
      - name: byobu
      - name: bzip2
      - name: ca-certificates
      - name: cgroup-tools
      - name: checkpolicy
      - name: cloc
      - name: cloud-initramfs-dyn-netconf
      - name: cloud-initramfs-growroot
      - name: cloud-utils
      - name: cmake
      - name: cmake-data
      - name: command-not-found
      - name: console-setup
      - name: console-setup-linux
      - name: coreutils
      - name: cowsay
      - name: cpio
      - name: cpp
      - name: cracklib-runtime
      - name: cron
      - name: curl
      - name: cvs
      - name: dash
      - name: dbus
      - name: dbus-x11
      - name: dc
      - name: dconf-gsettings-backend
      - name: dconf-service
      - name: dctrl-tools
      - name: debconf
      - name: debconf-i18n
      - name: debconf-utils
      - name: debhelper
      - name: debian-archive-keyring
      - name: debian-keyring
      - name: debianutils
      - name: debsums
      - name: devscripts
      - name: dh-lua
      - name: dh-python
      - name: dictionaries-common
      - name: diffutils
      - name: dirmngr
      - name: discount
      - name: discover
      - name: discover-data
      - name: distro-info
      - name: distro-info-data
      - name: dmidecode
      - name: dmsetup
      - name: docutils-common
      - name: dos2unix
      - name: dpkg
      - name: dpkg-dev
      - name: duplicity
      - name: e2fslibs
      - name: e2fsprogs
      - name: eject
      - name: elinks
      - name: elinks-data
      - name: elixir
      - name: emacs-nox
      - name: emacs24-bin-common
      - name: emacs24-common
      - name: emacs24-nox
      - name: emacsen-common
      - name: encfs
      - name: erlang-asn1
      - name: erlang-base
      - name: erlang-crypto
      - name: erlang-inets
      - name: erlang-mnesia
      - name: erlang-os-mon
      - name: erlang-public-key
      - name: erlang-runtime-tools
      - name: erlang-snmp
      - name: erlang-ssl
      - name: euca2ools
      - name: exuberant-ctags
      - name: fakeroot
      - name: ferm
      - name: figlet
      - name: file
      - name: findutils
      - name: firejail
      - name: fish
      - name: fish-common
      - name: fontconfig
      - name: fontconfig-config
      - name: fonts-dejavu-core
      - name: fonts-lyx
      - name: frotz
      - name: fuse
      - name: g++
      - name: gawk
      - name: gcc
      - name: gconf-service
      - name: gconf2
      - name: gconf2-common
      - name: gdb
      - name: geoip-database
      - name: gettext
      - name: gettext-base
      - name: gforth
      - name: gforth-common
      - name: gforth-lib
      - name: ghc
      - name: gir1.2-glib-2.0
      - name: git-email
      - name: git-man
      - name: glances
      - name: glib-networking
      - name: glib-networking-common
      - name: glib-networking-services
      - name: gnuchess
      - name: gnugo
      - name: gnupg-agent
      - name: gnupg2
      - name: gnuplot-data
      - name: gnuplot-nox
      - name: golang-go
      - name: golang-src
      - name: gpgv
      - name: grep
      - name: groff-base
      - name: grub-common
      - name: grub-pc
      - name: grub-pc-bin
      - name: grub2-common
      - name: gsettings-desktop-schemas
      - name: gsfonts
      - name: guile-2.0
      - name: guile-2.0-dev
      - name: guile-2.0-libs
      - name: gyp
      - name: gzip
      - name: haveged
      - name: hddtemp
      - name: hostname
      - name: html2text
      - name: htop
      - name: httpie
      - name: iamerican
      - name: ibritish
      - name: ieee-data
      - name: ienglish-common
      - name: ifupdown
      - name: imagemagick
      - name: imagemagick-6.q16
      - name: imagemagick-common
      - name: info
      - name: init
      - name: init-system-helpers
      - name: initramfs-tools
      - name: initscripts
      - name: insserv
      - name: install-info
      - name: installation-report
      - name: intltool-debian
      - name: iotop
      - name: ipcalc
      - name: iperf
      - name: iproute
      - name: iproute2
      - name: iptables
      - name: iputils-ping
      - name: ipxe-qemu
      - name: irssi
      - name: isc-dhcp-client
      - name: isc-dhcp-common
      - name: iso-codes
      - name: ispell
      - name: java-common
      - name: javascript-common
      - name: joe
      - name: john
      - name: john-data
      - name: jq
      - name: kbd
      - name: kexec-tools
      - name: keyboard-configuration
      - name: klibc-utils
      - name: kmod
      - name: krb5-locales
      - name: ksh
      - name: ldap-utils
      - name: less
      - name: lftp
      - name: libpam-systemd
      - name: libsqlite3-dev
      - name: linux-image-amd64
      - name: lm-sensors
      - name: locales
      - name: locales-all
      - name: locate
      - name: login
      - name: logrotate
      - name: lsb-base
      - name: lsb-release
      - name: lsof
      - name: ltrace
      - name: lua5.1
      - name: lua5.2
      - name: lua5.3
      - name: luajit
      - name: luarocks
      - name: lynx
      - name: lynx-cur
      - name: m4
      - name: man-db
      - name: manpages
      - name: manpages-dev
      - name: mat
      - name: mawk
      - name: mc
      - name: mc-data
      - name: mime-support
      - name: mksh
      - name: mlock
      - name: mosh
      - name: mount
      - name: mtr
      - name: multiarch-support
      - name: mutt
      - name: mysql-common
      - name: nano
      - name: ncdu
      - name: ncurses-base
      - name: ncurses-bin
      - name: ncurses-doc
      - name: ncurses-term
      - name: net-tools
      - name: netbase
      - name: netcat-traditional
      - name: nethack-common
      - name: nethack-console
      - name: nfacct
      - name: nmap
      - name: node-abbrev
      - name: node-ansi
      - name: node-ansi-color-table
      - name: node-archy
      - name: node-async
      - name: node-block-stream
      - name: node-combined-stream
      - name: node-cookie-jar
      - name: node-delayed-stream
      - name: node-forever-agent
      - name: node-form-data
      - name: node-fstream
      - name: node-fstream-ignore
      - name: node-github-url-from-git
      - name: node-glob
      - name: node-graceful-fs
      - name: node-gyp
      - name: node-inherits
      - name: node-ini
      - name: node-json-stringify-safe
      - name: node-lockfile
      - name: node-lru-cache
      - name: node-mime
      - name: node-minimatch
      - name: node-mkdirp
      - name: node-mute-stream
      - name: node-node-uuid
      - name: node-nopt
      - name: node-normalize-package-data
      - name: node-npmlog
      - name: node-once
      - name: node-osenv
      - name: node-qs
      - name: node-read
      - name: node-read-package-json
      - name: node-request
      - name: node-retry
      - name: node-rimraf
      - name: node-semver
      - name: node-sha
      - name: node-sigmund
      - name: node-slide
      - name: node-tar
      - name: node-tunnel-agent
      - name: node-underscore
      - name: node-which
      - name: nodejs
      - name: nodejs-dev
      - name: nodejs-legacy
      - name: nscd
      - name: nslcd
      - name: nslcd-utils
      - name: oidentd
      - name: openbios-ppc
      - name: openbios-sparc
      - name: openhackware
      - name: openntpd
      - name: openssh-client
      - name: openssh-sftp-server
      - name: openssl
      - name: os-prober
      - name: p7zip
      - name: pandoc
      - name: pandoc-data
      - name: parallel
      - name: parted
      - name: pass
      - name: passwd
      - name: patch
      - name: pciutils
      - name: pep8
      - name: perl
      - name: perl-base
      - name: perl-modules
      - name: php-cgi
      - name: php-cli
      - name: php-common
      - name: php-curl
      - name: php-fpm
      - name: php-json
      - name: php-mysql
      - name: php-sqlite3
      - name: pidgin-data
      - name: pinentry-curses
      - name: pkg-config
      - name: po-debconf
      - name: policykit-1
      - name: poppler-data
      - name: procps
      - name: psmisc
      - name: pv
      - name: pwgen
      - name: pyflakes
      - name: python
      - name: python-apt
      - name: python-apt-common
      - name: python-audit
      - name: python-backports.ssl-match-hostname
      - name: python-boto
      - name: python-cffi
      - name: python-characteristic
      - name: python-chardet
      - name: python-cheetah
      - name: python-colorama
      - name: python-configobj
      - name: python-crypto
      - name: python-cryptography
      - name: python-dateutil
      - name: python-debian
      - name: python-debianbts
      - name: python-decorator
      - name: python-defusedxml
      - name: python-dev
      - name: python-distlib
      - name: python-distro-info
      - name: python-docutils
      - name: python-ecdsa
      - name: python-flake8
      - name: python-gdbm
      - name: python-geoip
      - name: python-gi
      - name: python-hachoir-core
      - name: python-hachoir-parser
      - name: python-html5lib
      - name: python-httplib2
      - name: python-ipy
      - name: python-jinja2
      - name: python-json-pointer
      - name: python-jsonpatch
      - name: python-ldap
      - name: python-lockfile
      - name: python-lxml
      - name: python-markupsafe
      - name: python-matplotlib-data
      - name: python-mccabe
      - name: python-minimal
      - name: python-mock
      - name: python-mutagen
      - name: python-ndg-httpsclient
      - name: python-netaddr
      - name: python-networkx
      - name: python-newt
      - name: python-nose
      - name: python-numpy
      - name: python-oauth
      - name: python-openssl
      - name: python-paramiko
      - name: python-pdfrw
      - name: python-pip
      - name: python-pkg-resources
      - name: python-ply
      - name: python-potr
      - name: python-prettytable
      - name: python-pyasn1
      - name: python-pyasn1-modules
      - name: python-pycparser
      - name: python-pygments
      - name: python-pyparsing
      - name: python-reportlab
      - name: python-reportlab-accel
      - name: python-requestbuilder
      - name: python-requests
      - name: python-roman
      - name: python-serial
      - name: python-service-identity
      - name: python-setuptools
      - name: python-six
      - name: python-soappy
      - name: python-sss
      - name: python-stevedore
      - name: python-talloc
      - name: python-tox
      - name: python-twisted
      - name: python-twisted-bin
      - name: python-twisted-conch
      - name: python-twisted-core
      - name: python-twisted-mail
      - name: python-twisted-names
      - name: python-twisted-news
      - name: python-twisted-runner
      - name: python-twisted-web
      - name: python-twisted-words
      - name: python-tz
      - name: python-urllib3
      - name: python-virtualenv
      - name: python-websocket
      - name: python-wheel
      - name: python-wstools
      - name: python-yaml
      - name: python-zope.interface
      - name: python2.7
      - name: python2.7-dev
      - name: python2.7-minimal
      - name: python3
      - name: python3-apt
      - name: python3-bottle
      - name: python3-chardet
      - name: python3-colorama
      - name: python3-crypto
      - name: python3-decorator
      - name: python3-dev
      - name: python3-distlib
      - name: python3-html5lib
      - name: python3-jinja2
      - name: python3-markupsafe
      - name: python3-minimal
      - name: python3-numpy
      - name: python3-pip
      - name: python3-pkg-resources
      - name: python3-psutil
      - name: python3-py
      - name: python3-pyasn1
      - name: python3-pysnmp4
      - name: python3-reportbug
      - name: python3-requests
      - name: python3-scipy
      - name: python3-setuptools
      - name: python3-six
      - name: python3-software-properties
      - name: python3-urllib3
      - name: python3-venv
      - name: python3-virtualenv
      - name: python3-wheel
      - name: qalc
      - name: qemu-slof
      - name: qemu-system-common
      - name: qemu-user
      - name: qemu-utils
      - name: qprint
      - name: qtcore4-l10n
      - name: ranger
      - name: readline-common
      - name: redis-server
      - name: redis-tools
      - name: remind
      - name: reportbug
      - name: reptyr
      - name: resolvconf
      - name: rsync
      - name: rsyslog
      - name: rtorrent
      - name: ruby
      - name: rubygems-integration
      - name: samba-libs
      - name: sbcl
      - name: screen
      - name: seabios
      - name: sed
      - name: sensible-utils
      - name: sgml-base
      - name: shared-mime-info
      - name: shellcheck
      - name: siege
      - name: signing-party
      - name: silversearcher-ag
      - name: silversearcher-ag-el
      - name: slashem
      - name: slashem-common
      - name: socat
      - name: sqlite3
      - name: ssh
      - name: ssl-cert
      - name: sssd
      - name: sssd-ad
      - name: sssd-ad-common
      - name: sssd-common
      - name: sssd-ipa
      - name: sssd-krb5
      - name: sssd-krb5-common
      - name: sssd-ldap
      - name: sssd-proxy
      - name: sssd-tools
      - name: startpar
      - name: stow
      - name: strace
      - name: subversion
      - name: sudo
      - name: swaks
      - name: sysstat
      - name: tar
      - name: task-english
      - name: tasksel
      - name: tasksel-data
      - name: tcl
      - name: tcl-tls
      - name: tcl8.5
      - name: tcl8.6
      - name: tcllib
      - name: tcpd
      - name: telnet
      - name: tig
      - name: tmux
      - name: toilet
      - name: toilet-fonts
      - name: topgit
      - name: traceroute
      - name: tree
      - name: tudu
      - name: tzdata
      - name: ucf
      - name: udev
      - name: units
      - name: unzip
      - name: urlview
      - name: usbutils
      - name: util-linux
      - name: util-linux-locales
      - name: vim-common
      - name: vim-nox
      - name: vim-runtime
      - name: vim-tiny
      - name: virtualenv
      - name: virtualenv-clone
      - name: virtualenvwrapper
      - name: w3m
      - name: wamerican
      - name: weechat
      - name: weechat-core
      - name: weechat-curses
      - name: weechat-lua
      - name: weechat-plugins
      - name: weechat-perl
      - name: weechat-python
      - name: wget
      - name: whiptail
      - name: whois
      - name: wyrd
      - name: xauth
      - name: xdg-user-dirs
      - name: xkb-data
      - name: xml-core
      - name: xz-utils
      - name: zile
      - name: zip
      - name: zlib1g
      - name: zlib1g-dev
      - name: znc
      - name: zpaq
      - name: zsh
      - name: zsh-common
